// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcPSkK-9ru0hWCufQcCuAJqlPRI3T3ou4',
    appId: '1:123539295838:web:be8d273ad18406b0382ecf',
    messagingSenderId: '123539295838',
    projectId: 'memont-v2',
    authDomain: 'memont-v2.firebaseapp.com',
    storageBucket: 'memont-v2.appspot.com',
    measurementId: 'G-GDKN6PM5YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX5P9_syVoZjHZGRSzbzx59FzIyTLQ6Dc',
    appId: '1:123539295838:android:98a26bbf960d1855382ecf',
    messagingSenderId: '123539295838',
    projectId: 'memont-v2',
    storageBucket: 'memont-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtqYkYb-YUyl6-zjcwddXHB8uW98UTAWs',
    appId: '1:123539295838:ios:13843f92e95ecf10382ecf',
    messagingSenderId: '123539295838',
    projectId: 'memont-v2',
    storageBucket: 'memont-v2.appspot.com',
    androidClientId:
        '123539295838-elbmird8cvhr4uhn803vdf021rl35v8o.apps.googleusercontent.com',
    iosClientId:
        '123539295838-55mqm0uqt6crf4kjil0rgo6vlbvhg6eh.apps.googleusercontent.com',
    iosBundleId: 'com.dingpie.memont',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtqYkYb-YUyl6-zjcwddXHB8uW98UTAWs',
    appId: '1:123539295838:ios:b051eb5b26e4aff7382ecf',
    messagingSenderId: '123539295838',
    projectId: 'memont-v2',
    storageBucket: 'memont-v2.appspot.com',
    androidClientId:
        '123539295838-elbmird8cvhr4uhn803vdf021rl35v8o.apps.googleusercontent.com',
    iosClientId:
        '123539295838-v59kl5serkj1c0kjiicmesqa8abm91en.apps.googleusercontent.com',
    iosBundleId: 'com.dingpie.memont.RunnerTests',
  );
}
